### ISSUE TITLE
Update needed for 1.03?

### ISSUE THREAD

**Issue by JakenVeina** [The-Grand-Archives/ARMORED-CORE-VI-CT-TGA#1]
The "Failed to read game process. Make sure you've launched the game without EasyAntiCheat." message displays upon trying to enable the script. Yes, EAC is disabled, I've tried with both the steam_appid.txt and the start_protected_game.exe methods. I'm guessing this is because the game reports v1.03/30, while the script reports support for v1.02/30?

**Comment by inuNorii** [comment]
Nah if the version mismatched, you'd get this error:
`Your version of ARMORED CORE VI (1.01.2) might not be supported.`
`Supported version: 1.02`

The game's latest executable is version 1.02 (1.2.0.0), which is the only thing we actually use for game version checks.

Failed to read game process means it was unable to read the game process.
Usually that's caused by EAC preventing it, so might wanna check your running processes.

Either [System Informer](https://github.com/winsiderss/systeminformer) or [Process Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) should make it somewhat obvious if that's the case. Otherwise just look for `start_protected_game.exe` or EAC services running.

**Comment by JakenVeina** [comment]
The game launches without the EAC splash screen, and fails to connect to Epic Online Services.

There is no `start_protected_game.exe` running, nor any other process with "EAC" or similar in the description.

`armoredcore6.exe` appears within the list of attachable processes, within Cheat Engine.

I don't know what I would look for outside of those things.

**Comment by inuNorii** [comment]
Could you try launching CE without the table, attach to `armoredcore6.exe`, and then run these two lines of code in CE's lua console:
`print(string.format("0x%x", getAddressSafe("armoredcore6.exe")))`
`print(string.format("0x%x", getFileVersion(enumModules()[1].PathToFile)))`

To open the lua console, click on the `Memory View` button in the main CE window and then hit `Ctrl+L`.
The result should be the processes' base address and executable version.

**Comment by JakenVeina** [comment]
```
print(string.format("0x%x", getAddressSafe("armoredcore6.exe")))
print(string.format("0x%x", getFileVersion(enumModules()[1].PathToFile)))

Error:[string "print(string.format("0x%x", getAddressSafe("a..."]:1: bad argument #2 to 'format' (no value)
Script Error
```

It occurred to me that I experienced some nonsense behavior with Elden Ring scripts sometime last year, that ultimately ended up being a corrupted installation of CE. I went ahead and wiped and re-installed CE 7.5 and everything seems to be fine now.

Thanks for your time, regardless.
